urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.views.generic.simple import direct_to_template
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('homepage.urls')),
    url(r'^login/',include('login.urls')),
    url(r'^footer/', include('footer.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^',include('website.urls')),
    url(r'^greenvichar/', include('greenvichar.urls')),
    url(r'^company/$', direct_to_template,{'template':'directory/company.htm'},name='company'),
    url(r'^contactus/$', direct_to_template,{'template':'contactus.html'},name='contactus'),
#     url(r'^greenvichar/article/$', direct_to_template,{'template':'greenvichar/article.html'},name='article'),
#     url(r'^greenvichar/article/listing', direct_to_template,{'template':'greenvichar/listing.html'},name='article'),
#     url(r'^category/$', direct_to_template,{'template':'directory/keyword.html'},name='category'),
#     url(r'^search/$', direct_to_template,{'template':'directory/searchresult.htm'},name='search'),
    # url(r'^$', 'gogreen.views.home', name='home'),
    # url(r'^gogreen/', include('gogreen.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns("django.views",
        url(r'^media(?P<path>.*)/$',
            "static.serve", {
            "document_root": settings.MEDIA_ROOT,
        })
    )

website/models.py
from choices import YEAR_CHOICES, \
    TURNOVER_CHOICES, EMP_CHOICES, RATING_CHOICES
from django.contrib.auth.models import User
from django.db import models
from tinymce.models import HTMLField
from utils import get_image_by_size
from django.conf import settings
from datetime import datetime as dt
import json


class Blog(models.Model):
    title = models.CharField(max_length=200)
    linkurl = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, upload_to='uploads/blogimage', blank=True)
    text = models.TextField(null=True, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return self.title
    
    def save(self):
        super(Blog, self).save()
        if self.image:
            thumbname = get_image_by_size(self.image,'blog')
            self.image = 'uploads/blogimage/' + thumbname
        super(Blog, self).save()
     
     
class BusinessType(models.Model):
    name = models.CharField(max_length=20)
    
    def __unicode__(self):
        return self.name 

class Company(models.Model):
    company_name = models.CharField(max_length=200)
    company_tagline = models.CharField(max_length=200, null=True, blank=True)
    meta_desc = models.CharField(null=True, blank=True, verbose_name='Meta Description', max_length=50)
    meta_kword = models.CharField(max_length=50, null=True, blank=True, verbose_name='Meta Keywords')
    address = models.CharField(max_length=200)
    city = models.IntegerField(max_length=50)
    state = models.IntegerField(max_length=50)
    mobile = models.CharField(max_length=100, null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    contact_person = models.CharField(max_length=30, null=True, blank=True)
    contact_email = models.EmailField(null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    business_type = models.ManyToManyField('BusinessType')
    business_description = models.TextField(null=True)
    deals_in = models.TextField(null=True,blank=True)
    green_o_meter = models.CharField(max_length=100, null=True, blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES, default=0)
    subcategory = models.ManyToManyField('Subcategory')
    year_founded = models.IntegerField(choices=YEAR_CHOICES, null=True, blank=True)
    no_of_emp = models.IntegerField(choices=EMP_CHOICES, null=True, blank=True)
    turnover = models.IntegerField(choices=TURNOVER_CHOICES, null=True, blank=True)
    certifications = models.FileField(upload_to='uploads/comp_certi/',null=True, blank=True)
    company_logo = models.ImageField(upload_to='uploads/comp_logo/', null=True, blank=True)
    brouchers = models.FileField(upload_to='uploads/comp_downloads/',null=True, blank=True, verbose_name='brouchers(if any)')
    created_date = models.DateField(auto_now=True)
    modified_date = models.DateField(auto_now=True)
    modified_by = models.ForeignKey(User)
    
    def __unicode__(self):
        return self.company_name
    
           
    def save(self,*args,**kwargs):
        super(Company, self).save()
        if self.company_logo:
            thumbname = get_image_by_size(self.company_logo,'company_logo')
            self.company_logo = 'uploads/comp_logo/' + thumbname
#         create_companyjson()
        super(Company, self).save()
        
    def get_business_type(self):
        b_types = BusinessType.objects.filter(company=self).values_list('name',flat=True)
        return ','.join(list(b_types))
    
    def get_green_o_meter(self):
        objs = []
        if self.green_o_meter:
            val = self.green_o_meter
            objs = GreenOMeter.objects.filter(pk__in=val.split(','))
        return objs
    
    def get_city(self):
        city = City.objects.filter(id=self.city)
        return city.name
    
    def get_state(self):
        state = State.objects.filter(id=self.state)
        return state.name

# def create_companyjson():
#     companies = Company.objects.all().values_list('company_name',flat=True)
# #     company_json = json.dumps({'company':companies})
#     f = open('media/js/auto_companies.js','w')
#     text = 'var companies = ' + 
#     f.write(companies)
 
class CompanyProductImg(models.Model):
    company = models.ForeignKey('Company')
    image = models.ImageField(upload_to='uploads/comp_imgs')

    def save(self):
        super(CompanyProductImg, self).save()
    	if self.image:
    	    thumbname = get_image_by_size(self.image,'comp_prod_img')
    	    self.image = 'uploads/comp_imgs/' + thumbname
    	super(CompanyProductImg, self).save()

class Comment(models.Model):
    company = models.ForeignKey('Company')
    name = models.CharField(max_length=200)
    email = models.EmailField()
    text = HTMLField(max_length=1000)
    creation_date = models.DateTimeField(auto_now_add=True)
    moderation_date = models.DateTimeField(auto_now=True) 
    status = models.IntegerField(choices=((0,'Submitted'),(1,'Accepted'),(2,'Rejected')),default=0)
    done_by = models.ForeignKey(User, null=True)

class ContactUs(models.Model):
    company = models.ForeignKey('Company')
    name = models.CharField(max_length=200)
    email = models.EmailField()
    text = HTMLField(max_length=1000)
    creation_date = models.DateTimeField()
    moderation_date = models.DateTimeField() 
    status = models.IntegerField(choices=((0,'Submitted'),(1,'Viewed'),(2,'Declined')), default=0)
    done_by = models.IntegerField(null=True)
    

class GreenOMeter(models.Model):
    name = models.CharField(max_length=200)
    icon = models.ImageField(upload_to ='uploads/greenometer/',null=True,blank=True)
    
    def __unicode__(self):
        return self.name
    
    def save(self):
        super(GreenOMeter, self).save()
        if self.icon:
            thumbname = get_image_by_size(self.icon,'green_o_meter')
            self.icon = 'uploads/greenometer/' + thumbname
        super(GreenOMeter, self).save()

class CatManager(models.Manager):
    def get_query_set(self):
        new_set = []
        queryset = super(CatManager, self).get_query_set()
        for query in queryset:
            if query.subcategory_set.count():
                new_set.append(query)
        return new_set

class Category(models.Model):
    name = models.CharField(max_length=250)
    created_date = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    sort_order = models.IntegerField(default=1)
    icon = models.ImageField(upload_to='uploads/category')
    objects = models.Manager()
    has_sub_objs = CatManager()
    
    def __unicode__(self):
        return self.name

class Subcategory(models.Model):
    category = models.ManyToManyField(Category)
    name = models.CharField(max_length=250)
    meta_desc = models.CharField(null=True, blank=True, verbose_name='Meta Description', max_length=50)
    meta_kword = models.CharField(max_length=50, null=True, blank=True, verbose_name='Meta Keywords')
    created_date = models.DateTimeField(auto_now_add=True)
    is_deleted = models.BooleanField(default=False)
    sort_order = models.IntegerField(default=1)
    
    def __unicode__(self):
        return self.name         


class PopularKeyword(models.Model):
    keyword = models.CharField(max_length=200)
    timestamp = models.DateTimeField(auto_now=True)
    subcat = models.ManyToManyField('Subcategory')
    def __unicode__(self):
        return self.keyword
    
    
class State(models.Model):
    name = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.name
    
class City(models.Model):
    name = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.name

templates/directory/categ-subcateg.htm
<div class="span4 pull-left leftnav" ><h2>Browse Categories</h2>
{% for cat in cats %}
   <a href="javascript:void(0)">
      <h3 id="{{cat.id}}" class="cls_categ">
          {% if cat.icon %}
          <img src="{{ MEDIA_URL }}{{ cat.icon }}" class="pull-left" alt="{{cat}}" />
          {% endif %}
          <span class="pull-left">{{cat}}</span>
      </h3>
   </a>
   <ul id="sub_{{cat.id}}" class="cls_subcateg {% if not categ.0.id == cat.id %}disable{% endif %}">
   {% for sub in cat.subcategory_set.all %}
       <li><a {% if subcat.id == sub.id %} class="selected"{% endif %} href="{% url view_category cat.name|slugify sub.name|slugify sub.id %}">{{sub}}</a></li>
   {% endfor %}
   </ul>
    <div class="bdr"></div>
{% endfor %}
</div>

templates/directory/company.htm
{% extends "layoutbase.html" %}

{% block title %}{{comp.company_name}} - IndiaGetGreen{% endblock title %}
{% block meta %}
{{ block.super }}
    <meta property="og:type" content="website" />
    <meta property="og:title" content="{{comp.company_name}}" />
    <meta itemprop="title" content="{{comp.company_name}}" />
    <meta property="og:image" content="{{url_prefix}}media/images/200x200.jpg" />
    <meta itemprop="image" content="{{url_prefix}}media/images/200x200.jpg " />
    <meta property="og:url" content="{{url_prefix}}{{ comp.company_name|slugify }}/{{ comp.id }}/" />
    <meta itemprop="url" content="{{url_prefix}}{{ comp.company_name|slugify }}/{{ comp.id }}/" />
    <meta property="og:description" content="{{comp.business_description|removetags:'p b span br ul li strong ol'|safe|truncatewords:40}}" />
    <meta name="Description" content="{{comp.business_description|removetags:'p b span br ul li strong ol'|safe|truncatewords:40}}" />
    <meta name="keywords" content="{{comp.deals_in}}" />
    <meta name="twitter:card" content="summary">
    <meta name="twitter:url" content="{{url_prefix}}{{ comp.company_name|slugify }}/{{ comp.id }}/" />
    <meta name="twitter:title" content="{{comp.company_name}}" />
    <meta name="twitter:description" content="{{comp.business_description|removetags:'p b span br ul li strong ol'|safe|truncatewords:50}}" />
    <meta name="twitter:image" content="{{url_prefix}}media/images/100x100.jpg" />
    {% if comp.state %}<meta name="geo.placename" content="{{ comp.state }}"/>{% endif %}
    <link rel="canonical" href="{{url_prefix}}{{ comp.company_name|slugify }}/{{ comp.id }}/" />
{% endblock meta %}

{% block bodycontent %}
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=564979820231984";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>

<div id="content">
    <div class="container" itemscope itemtype="http://schema.org/Company">

    <ul class="breadcrumb w100">
    <li><a href="{% url index %}">Home</a><span class="divider">&gt;</span></li><li class="active"><a href="/{{ cats.0.name|slugify}}/{{sub.name|slugify}}/{{sub.id }}">Categories</a>&nbsp;&nbsp;&gt;&nbsp;&nbsp;{{comp.company_name}}</li>
    <li class="pull-right">

        <div class="fb-like" data-href="{{url_prefix}}{{ comp.company_name|slugify }}/{{ comp.id }}/"
             data-width="100" data-layout="button_count" data-show-faces="false" data-send="false"></div>

    </li>

        <li class="pull-right">
           <a href="https://www.facebook.com/sharer/sharer.php?u={{url_prefix}}{{ comp.company_name|slugify }}/{{ comp.id }}/" target="_blank"> <span class="fbtw"></span></a>
            <a href="http://twitter.com/intent/tweet?text={{ cats.0.name|slugify}}&amp;url={{url_prefix}}{{ comp.company_name|slugify }}/{{ comp.id }}/" target="_blank"> <span class="fbtw tw"></span></a>
        </li>

      </ul>
      <div class="comptop pull-left">
          {% if comp.company_logo %}
          <img itemprop="image" src="{{MEDIA_URL}}{{comp.company_logo}}" alt="" />
          {% endif %}
          <h1 itemprop="name">{{comp.company_name}}</h1>
    {% if comp.company_tagline %}
          <h2 {% if not comp.company_logo %}style="width:98%"{% endif %}>  {{comp.company_tagline}}</h2>
{% endif %}

      <div class="p">

          <ul>

              {% if comp.year_founded %}<li><b>Year Founded:</b> {{comp.year_founded}}</li>{% endif %}
              {% if comp.turnover %}<li><b>Turnover:</b> {{ comp.get_turnover_display }} Crores</li>{% endif %}
              {% if comp.no_of_emp %}<li><b>No. of Employees:</b> {{comp.get_no_of_emp_display}}</li>{% endif %}
          </ul>
          <em>  <b>Business Profile:</b> {{comp.get_business_type}}</em>
          <b>Deals in:</b> {{comp.deals_in}}
      <span class="dwnloads">
        {% if comp.brouchers or comp.certifications %}
          <b>Downloads:</b>{% endif %}
          {% if comp.brouchers %}<a href="{{MEDIA_URL}}{{comp.brouchers}}" target="_blank">Broucher</a>{% endif %}{% if comp.brouchers and comp.certifications %},{% endif %}
          {% if comp.certifications %}<a href="{{MEDIA_URL}}{{comp.certifications}}" target="_blank">Certificate</a>{% endif %}

{% comment %}
          {% if comp.city %}
          <b>City:</b> {{  comp.city.name }}
      {% endif %}
          {% if comp.state %}
              <b>State:</b> {{  comp.get_state_display }}
          {% endif %}
     {% endcomment %}
      </span>
      </div>

      <div class="clearfix"></div>
      </div>
      
      <div class="span12 pull-left ">
      <div class=" buisness">
   <h2>Business Description</h2>
      
      <span itemprop="description">{{comp.business_description}}</span>
      </div>

      {% if comp.get_green_o_meter %}
      
      <div class=" buisness">
   <h2>   Green-o-meter <em>(How is it green?)</em></h2>
   
   <ul>
   {% for obj in comp.get_green_o_meter %}
       <li><img src="{{MEDIA_URL}}{{obj.icon}}" alt=""></li>
   {% endfor %}
   </ul>
   
   
   </div>
   {% endif %}
   
   <div class=" buisness">
   <h2> Contact Information</h2>

<div id="googlemap" >
       {{comp.address}}
   </div>

       <div class="contact">
{% if comp.contact_person %}
   <strong>Contact Person: {{comp.contact_person}}</strong><br>{% endif %}
   <ul>
       {% if comp.address %}
       <li><span class="ad"></span>
   {{comp.address}}</li>{% endif %}
   {% if  comp.mobile or comp.phone%}
  <li><span class="mo"></span>{{comp.mobile}} {% if comp.phone != None %}, {{comp.phone}}{% endif %}</li>
       {% endif %}
       {% if comp.website %}
       <li>	  <span class="web"></span>	<a rel="nofollow" href="{{ comp.website }}" target="_blank">{{ comp.website }}</a> </li>
       {% endif %}
       {% if comp.contact_email %}
       <li> <span class="email"></span><a href="mailto:{{contact_email}}">{{comp.contact_email}}</a></li>
    {% endif %}
   </ul></div>
 
   </div>

      </div>
        <div class="span8 pull-left bd">
<div class=" martop review">
<h2>Reviews</h2>

<form method='POST' action='{% url save_review %}' onsubmit="return false" id='id_formreview'>
 {% csrf_token %}
  <strong> Post your reviews
  </strong>
  <ul>
<li><input name="name" type="text" maxlength="70" class="required" placeholder="Name" holder="Name" /></li>
      <li><input name="email" type="text" maxlength="70" class="required email" placeholder="Email" holder="Email"></li>
<li><textarea name="text" cols="" rows=""  class="required" placeholder="Message" holder="Message"></textarea></li>
<li><input name="submit" type="submit" value="Post my review"></li>
<input type='hidden' name='compId' value="{{comp.id}}" />
</ul>

</form>
{% for review in reviews %}
<p>{{ review.text }}</p>
<em>Posted by {{ review.name }}</em>{% endfor %}

{% if reviews %}
<a href="{% url view_company_reviews comp.company_name|slugify comp.id %}">View all reviews</a>
        {% endif %}
</div>
</div>
        {% if productimg %}
<div class="span4 pull-right">
{% comment %}
<div class="contactform"><strong>Contact form</strong><em>Fill the details below to get in touch </em>
<form action='{% url save_contact %}' onsubmit="return false" method='POST' id='id_formcontact'>
{% csrf_token %}
<ul>
	<li><input name="name" type="text" maxlength="70" class="required" placeholder="Name" holder="Name"></li>
	<li><input name="email" type="text" maxlength="70" class="required email" placeholder="Email" holder="Email"></li>
	<li><textarea name="text" cols="" rows="" placeholder="Message" holder="Message"></textarea></li>
	<input type='hidden' name='compId' value="{{comp.id}}" />
	<li><input name="" type="submit" value="Submit" /></li>
</ul>
</form>

</div>
{% endcomment %}


    <h2 class="h2prod">Product Gallery</h2>
<div class="martop prodimg pull-left w100 hidden-phone">

    <ul class="bxprodimg">
    {% for logo in productimg %}
       <li class="disable"> <img src="{{MEDIA_URL}}{{logo.image}}" alt="" /></li>
    {% endfor %}

</ul>
</div>

</div>
        {% endif %}
    </div>
</div>

<br/>

{% endblock bodycontent %}
{% block JSCustom %}
    {{ block.super }}
    <script type="text/javascript">
        $('.bxprodimg').bxSlider({
            minSlides: 1,
            maxSlides: 1,
            speed: 1000,
            mode:'fade',
            auto: true,
            randomStart:true,
            infiniteLoop:true
        });
    </script>
{% endblock JSCustom %}

templates/directory/reviews.html
<ul>
{% for review in reviews %}
<li>
{{ review.text }}
By:{{ review.name }}
</li>
{% endfor %}
</ul>

templates/directory/search.html
<form class="navbar-form pull-left" id="frmsearch" method='POST' action='{% url search %}'>
{% csrf_token %}
    <ul class="indsearch">  <li class="mm hidden-phone">Search by </li>
        <li class="mm">
        <input name="search_by" type="radio" checked="true" class="cls_type" value="by_product" />Products / Services
    </li><li class="mm">
        <input name="search_by" type="radio" class="cls_type" value="by_name" />Company Name </li>
        <li class="liinp"><input type="text" class="cls_comp span2" name ='keyword' holder="Search here" value="{{ keyword }}" placeholder="Search here"></li>
        <li class="lisel">{{cityform.city}}</li>
        <input type='hidden' name ="categ" value="{{categ.0.id}}" id="id_hdncateg" />
	<input type='hidden' name ="subcat" value="{{subcat.id}}" id="id_hdnsubcat" />
        <li> <input name="" type="submit" value=""></li></ul>
</form>